name: multi_vendor
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.22.0
  firebase_auth: ^3.8.0
  cloud_firestore: ^3.4.7
  firebase_storage: ^10.3.8
  image_picker: ^0.8.5+3
  uuid: ^3.0.6
  staggered_grid_view_flutter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/guest.jpg
    - assets/images/men/

  fonts:
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

